Add `ReportBody` wrapper around `sgx_report_body_t`
mobilecoinfoundation/sgx pull request #103
Opened 2022-08-25 21:28 UTC by nick-mobilecoin

2022-08-25 21:28 UTC, nick-mobilecoin commented
Current dependencies on/for this PR:
* main
  * **PR #91** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/91" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #86** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/86" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #92** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/92" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #103** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/103" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/103?utm_source=stack-comment).

2022-08-25 21:29 UTC, nick-mobilecoin commented on core/types/src/report.rs
> +/// A measurement
Up for suggestions on these transitive types.  Don't think it's ideal they're here but still flushing out where else they might be used.

2022-08-25 22:00 UTC, jcape requested changes
Recommend making `Measurement` an enum and using distinct types for MRENCLAVE and MRSIGNER hash types.

2022-08-26 23:04 UTC, nick-mobilecoin commented on core/types/src/report.rs
> +}
Brought in most of the Measurement logic from mc_attest_core

2022-08-30 17:39 UTC, jcape approved these changes
LGTM, but ideally we are just `derive(Default)` where applicable---the underlying FFI types should all have default on them now anyways, right?

2022-08-30 17:39 UTC, jcape commented on core/types/src/report.rs
> +}
Can this be derived?

2022-08-30 17:39 UTC, jcape commented on core/types/src/report.rs
> +impl Default for ReportBody {
Same Q: can this be derived?

2022-08-30 17:39 UTC, jcape commented on core/types/src/macros.rs
> +        }
Can we remove this and just derive it?

2022-08-30 21:02 UTC, nick-mobilecoin commented on core/types/src/report.rs
> +impl Default for ReportBody {
Done as part of #115

2022-08-30 21:02 UTC, nick-mobilecoin commented on core/types/src/macros.rs
> +        }
Done as part of #115

2022-09-02 17:34 UTC, awygle approved these changes

2022-09-02 18:08 UTC, nick-mobilecoin commented
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/103?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: C6ZyZ0Ggec8V0ksW3mYN

2022-09-02 18:08 UTC, merged