Add `mc-sgx-sdk-tools` crate
mobilecoinfoundation/sgx pull request #245
Opened 2023-01-04 17:58 UTC by nick-mobilecoin

### Motivation

### Future Work

2023-01-04 17:58 UTC, nick-mobilecoin commented
Current dependencies on/for this PR:
* main
  * **PR #245** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/245" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/245?utm_source=stack-comment).

2023-01-05 17:20 UTC, jcape approved these changes

2023-01-05 17:20 UTC, jcape requested changes
Sorry, approved too quick, could you use `sdk-tools` as the dir-name, to match the crate name? Thanks

2023-01-05 23:35 UTC, nick-mobilecoin commented
> Sorry, approved too quick, could you use `sdk-tools` as the dir-name, to match the crate name? Thanks

Renamed to directory to `sdk-tools`

2023-01-06 17:19 UTC, jcape approved these changes

2023-01-06 19:06 UTC, varsha888 approved these changes

2023-01-06 19:22 UTC, merged