Add Crev action w/ status comment to CI.
mobilecoinfoundation/sgx pull request #271
Opened 2023-02-09 00:56 UTC by jcape

- Add a new 'dependency-crev' job
- Print out a markdown table of dependencies which need reviews.

### Motivation

This is the first step towards automated dependabot approval based on existing reviews.

### Future Work

- Automatically merge PRs opened by dependabot which pass 'crev verify'

2023-02-09 00:56 UTC, jcape commented
Current dependencies on/for this PR:
* main
  * **PR #271** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/271" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/271?utm_source=stack-comment).

2023-02-10 17:02 UTC, nick-mobilecoin requested changes
The main change requested is consistency with the table sorting, whether it's supposed to be geiger or loc based.

2023-02-10 17:02 UTC, nick-mobilecoin commented on .github/workflows/ci.yaml
> +          cargo install cargo-crev || true
:wrench: double checking, the `|| true` is to work around already installed due to `rust-cache`

2023-02-10 17:38 UTC, jcape commented on .github/workflows/ci.yaml
> +            sort -t\| -n -k5 | \
I went back and forth on this, I think I'd prefer LoC since it means the easiest things to review are first up.

2023-02-10 17:39 UTC, jcape commented on .github/workflows/ci.yaml
> +          # - Skip any "local" dependencies
Yeah, but c.f. not having a `--color` that works...

2023-02-10 17:39 UTC, jcape commented on .github/crev.sh
> +#!/bin/bash
Correct, ty

2023-02-10 18:06 UTC, nick-mobilecoin approved these changes

2023-02-11 01:21 UTC, varsha888 approved these changes

2023-02-11 01:21 UTC, merged