Implement `Display` for `MiscellaneousSelect`
mobilecoinfoundation/sgx pull request #311
Opened 2023-04-03 19:40 UTC by samdealy

### Motivation

### Future Work

2023-04-03 19:40 UTC, samdealy commented
Current dependencies on/for this PR:
* main
  * **PR #308** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/308" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #310** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/310" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #311** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/311" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/311?utm_source=stack-comment).

2023-04-11 16:18 UTC, jcape requested changes

2023-04-11 16:18 UTC, jcape commented on core/types/src/attributes.rs
> +        write!(f, "MiscellaneousSelect: ")?;
```suggestion
```

2023-04-11 16:18 UTC, jcape commented on core/types/src/attributes.rs
> +        assert_eq!(display_string, expected_string);
```suggestion
        let display_string = format!("{}", miscellaneous_select);
        let expected_string = format!("0x0121_ABF8");

        assert_eq!(display_string, expected_string);
```

2023-04-11 18:29 UTC, samdealy commented on util/src/format.rs
> +pub fn fmt_hex(src: &[u8], f: &mut Formatter) -> core::fmt::Result {
Done.

2023-04-11 18:30 UTC, samdealy commented on core/types/src/attributes.rs
> +        assert_eq!(display_string, expected_string);
Done.

2023-04-11 18:55 UTC, jcape approved these changes

2023-04-11 19:18 UTC, merged